version: '3.8'
services:
  nextapp:
    image: teallen_front-nextapp  # use the pre-built image
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - teallen

networks:
  teallen:
    external: true
