version: '3.8'
services:
  nextapp:
    build: . # use the local Dockerfile
    restart: unless-stopped
    container_name: ${NEXTAPP_CONTAINER_NAME}
    ports:
      - ${NEXTAPP_DOCKER_PORTS}
    environment:
      NODE_ENV: production
    networks:
      - teallen

networks:
  teallen:
    external: true
