version: '3.8'
services:
  test-nextapp:
    build: . # use the local Dockerfile
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      NODE_ENV: production
    networks:
      - teallen

networks:
  teallen:
    external: true
