import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="absolute bg-transparent text-white font-bold">
          <Link
            className="mx-2"
            href="/"
          >
            home
          </Link>
          <Link
            className="mx-2"
            href="/developer"
          >
            developer
          </Link>
          <Link
            className="mx-2"
            href="/teacher"
          >
            teacher
          </Link>
          <Link
            className="mx-2"
            href="/blog"
          >
            blog
          </Link>
          <Link
            className="mx-2"
            href="/contact"
          >
            contact
          </Link>
        </nav>
        <div>{children}</div>
      </body>
    </html>
  );
}

// TODO: compose placeholder nav
